test:
    JENKINS_URL: "http://jenkins.mxnet-ci.amazon-ml.com/"
    REGION: us-west-2
    CLOUDWATCH_METRIC_NAMESPACE: 'marco-jenkins-run-statistics4'
    DYNAMODB_TABLE_NAME: 'marco-test-jenkins-run-statistics4'

prod:
    JENKINS_URL: "http://jenkins.mxnet-ci.amazon-ml.com/"
    REGION: us-west-2
    CLOUDWATCH_METRIC_NAMESPACE: 'JenkinsRunStatistics'
    DYNAMODB_TABLE_NAME: 'JenkinsRunStatistics'

