test:
    JENKINS_URL: "http://jenkins.mxnet-ci-dev.amazon-ml.com/"
    REGION: us-west-2
    CLOUDWATCH_METRIC_NAMESPACE: 'chai-test'
    DYNAMODB_TABLE_NAME: 'chai-test'
    UNITTEST_ARTIFACT_REPOSITORY: 'mxnet-ci-dev-unittest-artifact'
prod:
    JENKINS_URL: "http://jenkins.mxnet-ci.amazon-ml.com/"
    REGION: us-west-2
    CLOUDWATCH_METRIC_NAMESPACE: 'JenkinsRunStatistics'
    DYNAMODB_TABLE_NAME: 'JenkinsRunStatistics'

