test:
    SECRET_ENDPOINT_URL: https://secretsmanager.us-west-2.amazonaws.com
    SECRET_ENDPOINT_REGION: us-west-2

prod:
    SECRET_ENDPOINT_URL: https://secretsmanager.us-west-2.amazonaws.com
    SECRET_ENDPOINT_REGION: us-west-2
    
